---
- name: Civilization code
  type: input
- name: Civilization name
  type: input
- name: Culture
  main: 
  clothing: 
  architecture: 
  genetic: 
  diet: 
  music: 
  structures: 
  wall_sets: 
  ai_names: 
- name: deities
  type: list
- name: getOptions('deities')

  description:
emblem: session/portraits/emblems/emblem_athenians.png
history: Athens, is the capital and largest city of Greece. Athens dominates the Attica region and is one of the world's oldest cities, with its recorded history spanning over 3,400 years and its earliest human presence started somewhere between the 11th and 7th millennium BC.
- name: selectable_in_game_setup
  type: confirm


start_entities: standard
civ_bonuses: attic
team_bonuses: attic

formations: attic
combat:
  preferred_distance: melee # defines starting entities and basic unit build tree
  melee: getMeleeWeapons() 
  ranged: getRangedWeapons()
  cavalry: 
  - javelin
  - sword
  weapons: attic
  armor: leather
  shield:
    melee: aspis
    ranged: pelte
  mercenaries:
    - thracians
    - scythians


politics:
  government: city states # <city states, league, empire, monarchy>
  communality: civilized # <Independent, civilized>

factions: attic
house_size: large # <small|large> (celts, iberians, indians, ptol are small) 
