name: Greek States 
version: 0.0.1
label: Greek States
url: 
description: Presently just a test mod
dependencies: ["0ad>=0.0.23"]
civilizations: ["hellenic"]   
    #  athen: true
    #  brit: false
    #  cart: false
    #  gaul: false
    #  iber: false
    #  kush: false
    #  mace: false
    #  maur: false
    #  pers: false
    #  ptol: false
    #  rome: false
    #  sele: false
    #  spart: false
citizen_soldier: true
soldiers_construct_siege: true

loot:
  collect_as: instant_resource # <treasure|instant_resource|loot>
  trade_carts_dropsite: true # <true|false|extra_unit>
  equipment_ratio: 0.2

defensive_structures: 
  houses_shoot: true
  houses_weaker: true
  houses_barricade_upgrade: true
  garrison_economic: true
  garrison_resource: true
  garrison_civic: true
  structures_less_capture_recovery: true
  structures_weaker: true

battle:
  armor: low
  health: medium
  damage: high
  wounded: true

experience:
  promote_across_class: true
  classes:
    - slave
    - citizen
    - citizen soldier
    - professional
    - champion
    - hero
    - mercenary
    - priest

agriculture:
  farms_used_and_regrow: true
  bushes_regrow: true
  farms_tiny_fields: true
  fauna_manure: true
  fauna_trickle: true
  fauna_consume_farms: true

phase:
  type: phase # <phase|age> whether to make phase researchable or to apply automatically when certain conditions - such as number of buildings - are met 
  territory: contiguous # <contiguous|global> whether to apply the phase to contiguous territories or globally.
