---
# Generic
code: athen
name: athenians
demonym: athenian
demonym_plural: athenians
deities: 
- name: Athena
  description:
emblem: session/portraits/emblems/emblem_athenians.png
history: Athens, is the capital and largest city of greece. athens dominates the attica region and is one of the world's oldest cities, with its recorded history spanning over 3,400 years and its earliest human presence started somewhere between the 11th and 7th millennium bC.
selectable_in_game_setup: True

start_entities: standard
civ_bonuses: attic
team_bonuses: attic
physical:
  height: 1.77 #metres
  weight: 90 #kg

formations: Attic
combat:
  preferred_distance: Melee # Defines Starting Entities And Basic Unit Build Tree
  melee: 
  - Spearman
  - Swordsman
  ranged:
  - Slinger
  - Javelineer
  - Archer
  cavalry: 
  - Javelineer
  - Swordsman
  weapons: Attic
  armor: Leather
  shield:
    melee: Aspis
    ranged: Pelte
  mercenaries:
  - Thracians
  - Scythians
  champions:
  - Spearman
  - Archer

culture: Hele
clothing: Attic, Thracian
architecture: Attic
genetic: Attic
diet: Mediterranean
music: Attic
build_tree: athenian
structures: Attic
wall_sets: Attic
ai_names: Attic

politics:
  government: City States # <city States, League, Empire, Monarchy>
  communality: Civilized # <Independent, Civilized>

factions: Attic
house_size: Large # <small|large> (celts, Iberians, Indians, Ptol Are Small) 
