code: chihann
culture: chinese
name: Hann
name_global: Hann (Chinese State)
history: https://en.wikipedia.org/wiki/Han_(state)

philosophy:
- legalist
civ_bonuses:
- chinese
- Name: Armor Mastery
  History: Known for making the best armor
  Description: Armor Techs -50% cost, -50% Research Time, Armor 50% Cheaper, Available in Village Phase.
  Source: https://www.ancient.eu/article/1143/armour-in-ancient-chinese-warfare/
heroes:
champions: Iron Face Masks
