# Hellenic
hellenic: &hellenic
- Name: Theatron
  Class: ''
  Emblem: ''
  History: Greek theatres were places where the immortal tragedies of Aeschylus, Sophocles
    and many other talented dramatists were staged to the delight of the populace.
    They were instrumental in enriching Hellenic culture.
  Requirements: ''
  Phase: City
  Special: The Hellenization civ bonus. Building a Theatron increases the territory
    effect of all buildings by 25%.

attic: &attic
- *hellenic
- Name: Gymnasion
  Class: ''
  Emblem: ''
  History: The Gymnasion was a vital place in Hellenic cities, where physical exercises
    were performed and social contacts established.
  Requirements: ''
  Phase: City
  Special: Train champion units and research technologies pertaining to champion units.
- Name: Prytaneion
  Class: ''
  Emblem: ''
  History: The Prytaneion is the meeting place for the city elders to dine and to
    make swift decisions.
  Requirements: ''
  Phase: City
  Special: Train heroes and research technology pertaining to heroes.
