attic: &attic
- Name: Delian League
  History: Shortly after the great naval victories at Salamis and Mykale, the Greek
    city-states instituted the so-called Delian League in 478 B.C., whose purpose
    was to push the Persians out of the Aegean region. The allied states contributed
    ships and money, while the Athenians offered their entire navy.
  Description: Allied Warships −25% construction time.
