# Village Phase
standard: &standard
- civic_center:
    village_phase: 
      entities:
      - Female Citizen
      - Infantry ${weapon.primary.melee}
      - Infantry ${weapon.primary.ranged}
      - Cavalry ${weapon.primary.default}
      technologies:
      - Town Phase
    town_phase:
      technologies:
      - City Phase
    city_phase:
      technologies:
      - Espionage
      - Counterintelligence
- house:
    village_phase: 
      entities:
      - Female Citizen
      - Loom
      - Fertility Festival
    town_phase: 
      technologies:
      - Home Garden
    city_phase: 
      technologies:
      - Manors
- farmstead:
    village_phase:
      technologies:
      - Wicker Baskets
      - Iron Plow
    town_phase:
      technologies:
      - Gather Training
    city_phase: 
      technologies:
      - Fertilizer
- storehouse:
    village_phase:
      technologies:
      - Iron Axe Heads
      - Servants
      - Wedge and Mallet
      - Baskets
    town_phase:
      technologies:
      - Stronger Axe
      - Serfs
      - Shaft Mining
      - Wheelbarrow
    city_phase:
      technologies:
      - Sharp Axe Heads
      - Slaves
      - Silver Mining
      - Horse Drawn Carts
- field:
- corral:
    village_phase: 
      technologies:
      - Stockbreeding
    town_phase: 
      technologies:
      - Cavalry Breeding
    city_phase:
      technologies:
      - Cavalry Speed Training
- dock:
    village_phase: 
      entities:
      - Fishing Boat
      technologies:
      - Fishing Net
      - Reinforced Hull
    town_phase: 
      entities:
      - Trade Ship
      - Light Warship
      technologies:
      - Salting Fish
      - Hyperzomata Undergirding
    city_phase: 
      technologies:
      - Naval Architects
      - Lead Hull Sheathing
- outpost:
    village_phase: 
      technologies:
      - Carrier Pigeons
      - Stone Foundations
    town_phase: 
    city_phase: 
- palisade:
    village_phase:
      upgrades:
      - Wooden Gate
    town_phase: 
    city_phase: 
- sentry_tower:
    village_phase: 
      technologies:
      - Sentries
    town_phase: 
      upgrades:
      - Defense Tower
    city_phase: 
- barracks:
    village_phase: 
      entities:
      - Infantry ${weapon.primary.melee}
      - Infantry ${weapon.primary.ranged}
      - Cavalry ${weapon.primary.default}
    town_phase: 
      entities:
      - Infantry ${weapon.secondary.melee}
      - Infantry ${weapon.secondary.ranged}
      - Cavalry ${weapon.primary.default}
    city_phase: 

# Town Phase
- temple:
    town_phase:
    - healer
    - healing_range_01
    - healing_rate_01
    city_phase:
    - healing_range_02
    - healing_rate_02
    - Divine Offerings (heal_temple)
    - Battlefield Medicine (health_regen_units)
- market:
    town_phase:
    - trader
    - cartography
    - diaspora
    - trade_convoys_speed
    - handicraft
    - commercial treaty
    city_phase:
    - trade_convoys_armor
    - advanced handicraft
- blacksmith:
    town_phase:
    - armor infantry 01 
    - armor cavalry 01 
    - attack infantry melee 01
    - attack infantry ranged 01
    - attack cavalry melee 01
    - attack cavalry ranged 01
    city_phase:
    - armor infantry 02
    - armor cavalry 02
    - attack infantry melee 02
    - attack infantry ranged 02
    - attack cavalry melee 02
    - attack cavalry ranged 02
    - iron hero armor
- defense_tower:
    town_phase:
    - sentries
    - crenallations
    - arrow shooters
    city_phase:
    - murder_holes
    - sturdy foundations
- stone_wall:
    town_phase:
    - gate
    - wall_turrent
    - geometric masonry
    - rubble materials
# City Phase
- wonder:
  city_phase:
  - glorius expansion
- siege_workshop:
  city_phase:
  - ${civ.siege_units}
  - siege_armor
  - siege_attack
  - siege_cost_metal
  - siege_cost_wood
- fortress:
  city_phase:
  - will_to_fight
