town:
  entities:
  - trader
  technologies:
  - cartography
  - diaspora
  - trade_convoys_speed
  - handicraft
  - commercial treaty
city:
  technologies:
  - trade_convoys_armor
  - advanced handicraft
